# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

default: &default
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  aws_region: <%= ENV["AWS_REGION"] %>
  aws_bucket: <%= ENV["AWS_BUCKET_NAME"] %>
  aws_host: <%= ENV["AWS_HOST"] %>
  sentry_enabled: false
  census_url: <%= ENV["CENSUS_URL"] %>
  census_active: <%= ENV["CENSUS_ACTIVE"].to_s == "true" %>
  voting_active: <%= ENV["VOTING_ACTIVE"].to_s == "true" %>
  voting_starts: <%= Time.parse(ENV.fetch("VOTING_STARTS", "2021-06-01 00:00:00 +0200")) %>
  voting_ends: <%= Time.parse(ENV.fetch("VOTING_ENDS", "2021-06-16 23:59:59 +0200")) %>
  skip_census_verification: <%= ENV["SKIP_CENSUS_VERIFICATION"].to_s == "true" %>
  sms:
    service_url: <%= ENV["SMS_SERVICE_URL"] %>
    proxy_url: <%= ENV["SMS_PROXY_URL"] %>
    username: <%= ENV["SMS_USERNAME"] %>
    password: <%= ENV["SMS_PASSWORD"] %>
    service_id: "<%= ENV['SMS_SERVICE_ID'] %>"
    sub_service_id: "<%= ENV['SMS_SUB_SERVICE_ID'] %>"
  omniauth:
    facebook:
      # It must be a boolean. Remember ENV variables doesn't support booleans.
      enabled: false
      app_id: <%= ENV["OMNIAUTH_FACEBOOK_APP_ID"] %>
      app_secret: <%= ENV["OMNIAUTH_FACEBOOK_APP_SECRET"] %>
    twitter:
      enabled: false
      api_key: <%= ENV["OMNIAUTH_TWITTER_API_KEY"] %>
      api_secret: <%= ENV["OMNIAUTH_TWITTER_API_SECRET"] %>
    google_oauth2:
      enabled: false
      icon_path: decidim/brands/google.svg
      client_id: <%= ENV["OMNIAUTH_GOOGLE_CLIENT_ID"] %>
      client_secret: <%= ENV["OMNIAUTH_GOOGLE_CLIENT_SECRET"] %>
  maps:
    api_key: <%= ENV["MAPS_API_KEY"] %>
  etherpad:
    server: <%= ENV["ETHERPAD_SERVER"] %>
    api_key: <%= ENV["ETHERPAD_API_KEY"] %>
    api_version: "1.2.1"

development:
  <<: *default
  secret_key_base: 9ab9f4128ed0ca5b6cb1fdc1de2d29357844c7c9a4ea3903764b9213590d52cbd922e7981338fff24a17fc76ed0bca33af226d78c703149c8c5edc3edddb3f32
  census_active: true
  voting_active: true
  skip_census_verification: true
  omniauth:
    developer:
      enabled: true
      icon: phone

test:
  <<: *default
  secret_key_base: 99f8b3d00b8552185fb3c52da8e3413d94551f21f1af5babe197dc4988966fbffef3676aa6a18965b37ee76ecc61c2a73f20575a6cb2893b21e54a0ab0f7616d
  omniauth:
    facebook:
      enabled: true
      app_id: fake-facebook-app-id
      app_secret: fake-facebook-app-secret
    twitter:
      enabled: true
      api_key: fake-twitter-api-key
      api_secret: fake-twitter-api-secret
    google_oauth2:
      enabled: true
      client_id:
      client_secret:

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  sentry_enabled: true
  email: "<%= ENV["EMAIL"] %>"
  smtp_address: <%= ENV["SMTP_ADDRESS"] || "smtp.sendgrid.net" %>
  smtp_port: "587"
  smtp_authentication: "plain"
  smtp_username: <%= ENV["SMTP_USERNAME"] || ENV["SENDGRID_USERNAME"] || "apikey" %>
  smtp_password: <%= ENV["SMTP_PASSWORD"] || ENV["SENDGRID_PASSWORD"] %>
  smtp_domain: <%= ENV["SMTP_DOMAIN"] || "heroku.com" %>
  smtp_starttls_auto: true
